# Generated by Django 4.2.6 on 2023-10-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('team_name', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('no_of_winning', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
